#!/bin/bash
help_link="https://github.com/hermanzdosilovic/scripts/tree/master/testcase-fit"
log_file=$HOME/.tcfit.log

if [[ $# -lt 4 ]]; then
  echo "usage: tcfit <inext> <outext> <name> <dest>"
  echo "
  <inext>
    extension of input test case file

  <outext>
    extension of output test case files

  <name>
    new name for test case group

  <dest>
    destination where test cases will be stored
  "
  echo "For more help and examples please visit $help_link"
  exit
fi

inext="$1"
outext="$2"
name="$3"
dest="$4"

start="$5"
if [[ ! $5 =~ ^[1-9][0-9]*$ ]]; then
  start="1"
fi

inputs=( $(find . -type f -regextype posix-egrep -regex "^.*/(.*\.|.{0})$inext(\..*|.{0})$" | sort) )
outputs=( $(find . -type f -regextype posix-egrep -regex "^.*/(.*\.|.{0})$outext(\..*|.{0})$" | sort) )
date > $log_file; echo >> $log_file
echo "Listing all found input test cases:" >> $log_file
printf "%s\n" "${inputs[@]}" >> $log_file; echo >> $log_file
echo "Listing all found output test cases:" >> $log_file
printf "%s\n" "${outputs[@]}" >> $log_file; echo >> $log_file

if [[ ${#inputs[@]} != ${#outputs[@]} ]]; then
  echo "ERROR: Number of input test cases and output test cases should be the same!" 1>&2
  echo "ERROR: Number of input test cases and output test cases should be the same!" >> $log_file
  echo "For more help and examples please visit $help_link" | tee -a $log_file
  exit
fi

if [ ! -d "$dest" ]; then
  echo "ERROR: Directory $dest not found" 1>&2
  echo "ERROR: Directory '$dest' not found" >> $log_file
  echo "For more help and examples please visit $help_link" | tee -a $log_file
  exit
fi

test_dir="$dest/test/$name"
mkdir -p "$test_dir"

for (( i=0; i<${#inputs[@]}; i++ )); do
  k="$(printf "%02d" $start)"
  start=$[$start+1]
  cp "${inputs[i]}" "$test_dir/$name.in.$k"
  echo "cp ${inputs[i]} $test_dir/$name.in.$k" | tee -a $log_file
  cp "${outputs[i]}" "$test_dir/$name.out.$k"
  echo "cp ${outputs[i]} $test_dir/$name.out.$k" | tee -a $log_file
  echo | tee -a $log_file
done

echo "All done. Updated $log_file"
