#!/bin/bash

# specify your C compiler
GCC=gcc

# specify your C++ compiler
GPP=g++

# find last modified .c or .cpp file
source=$(ls -tr *.{c,cpp,rb} 2>/dev/null | tail -1)
# get file extension
extension=${source##*.}
# get file name
name=${source%.*}

# if no file found then cannot continue
if [ "$source" == "" ]; then
    echo "ev: no file for execution"
    echo
    exit
fi

printf " - ${source} -\n"

# if there is no 'test' directory
if [ ! -d test ]; then
    echo "ev: directory 'test' does not exists"
    echo "- created 'test' directory"
    mkdir test
fi

# if check if tests exists
tests=$(ls test/${name}.*.in 2>/dev/null)
if [ "$tests" == "" ]; then
    echo "ev: test data does not exsist"
    for case in {1..6}; do
        touch test/${name}.$case.in
        touch test/${name}.$case.out
        echo "- created test/${name}.$case.in"
        echo "- created test/${name}.$case.out"
    done
    echo
    exit
fi

# compile source
if [ "$extension" == "c" ]; then
    errors=$($GCC ${source} 2>&1 > /dev/null)
elif [ "$extension" == "cpp" ]; then
    errors=$($GPP ${source} 2>&1 > /dev/null)
fi

# if compile errors occured then cannot continue
if [ "$errors" != "" ]; then
    echo "$errors"
    printf "ev: check compile errors\n\n"
    exit
fi

for fin in test/${name}.*.in; do
    # from input file make output file with same format
    fout=${fin%.*}.out
    echo "* $fin:"

    # if outout file exists compare output
    if [ -a $fout ]; then
        foutuser=${fin%.*}.user.out
        if [ -a ./a.out ]; then
            ./a.out < $fin > $foutuser
        else
            cat $fin | ruby $source > $foutuser
        fi
        cmp -s $fout $foutuser
        if [ $? -eq 1 ]; then
            echo "WRONG"
            echo "check $foutuser for help"
        else
            echo "CORRECT"
        fi
    else
        if [ -a ./a.out ]; then
            ./a.out < $fin
        else
            cat $fin | ruby $source
        fi
    fi

        # ./a.out < $fin

    echo
done

if [ -a ./a.out ]; then
    rm a.out
fi
